"""empty message

Revision ID: 069f916c3db1
Revises: ad6734b2358e
Create Date: 2019-12-17 15:15:44.873512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '069f916c3db1'
down_revision = 'ad6734b2358e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case_step_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_step_rank', sa.Integer(), nullable=True, comment='测试用例步骤'),
    sa.Column('test_case_action_title', sa.String(length=100), nullable=False, comment='测试操作标题'),
    sa.Column('test_case_action_input', sa.String(length=100), nullable=True, comment='测试操作输入参数'),
    sa.Column('test_case_action_output', sa.String(length=100), nullable=True, comment='测试操作输出参数'),
    sa.Column('test_case_log_id', sa.Integer(), nullable=True, comment='所属用例日志ID'),
    sa.Column('run_test_action_result', sa.Integer(), nullable=True, comment='测试操作执行结果:0失败,1成功'),
    sa.Column('action_start_time', sa.DateTime(), nullable=True, comment='测试步骤开始时间'),
    sa.Column('action_end_time', sa.DateTime(), nullable=True, comment='测试步骤结束时间'),
    sa.Column('run_test_case_times', sa.String(length=100), nullable=True, comment='测试步骤执行用时'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'),
    sa.ForeignKeyConstraint(['test_case_log_id'], ['test_case_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例结束时间',
               existing_nullable=True)
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例开始时间',
               existing_comment='测试步骤开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'run_test_action_result',
               existing_type=mysql.INTEGER(display_width=11),
               comment='测试用例操作执行结果:0失败,1成功',
               existing_comment='测试操作执行结果:0失败,1成功',
               existing_nullable=True)
    op.drop_column('test_case_log', 'error_msg')
    op.drop_column('test_case_log', 'test_case_action_input')
    op.drop_column('test_case_log', 'test_case_step_rank')
    op.drop_column('test_case_log', 'test_case_action_title')
    op.drop_column('test_case_log', 'test_case_action_output')
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_log', 'run_test_result',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='测试执行结果:0失败,1成功')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_log', 'run_test_result',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='测试执行结果:0失败,1成功')
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.add_column('test_case_log', sa.Column('test_case_action_output', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True, comment='测试操作输出参数'))
    op.add_column('test_case_log', sa.Column('test_case_action_title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False, comment='测试操作标题'))
    op.add_column('test_case_log', sa.Column('test_case_step_rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='测试用例步骤'))
    op.add_column('test_case_log', sa.Column('test_case_action_input', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True, comment='测试操作输入参数'))
    op.add_column('test_case_log', sa.Column('error_msg', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='错误信息'))
    op.alter_column('test_case_log', 'run_test_action_result',
               existing_type=mysql.INTEGER(display_width=11),
               comment='测试操作执行结果:0失败,1成功',
               existing_comment='测试用例操作执行结果:0失败,1成功',
               existing_nullable=True)
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤开始时间',
               existing_comment='测试用例开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试用例结束时间',
               existing_nullable=True)
    op.drop_table('test_case_step_log')
    # ### end Alembic commands ###
