"""empty message

Revision ID: 0763ac7124a4
Revises: fc67d66a621d
Create Date: 2019-09-23 11:21:13.912383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0763ac7124a4'
down_revision = 'fc67d66a621d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_management',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platformName', sa.String(length=100), nullable=False, comment='使用的手机操作系统'),
    sa.Column('platformVersion', sa.String(length=100), nullable=False, comment='手机操作系统的版本'),
    sa.Column('deviceName', sa.String(length=100), nullable=False, comment='使用的手机或模拟器类型'),
    sa.Column('appPackage', sa.String(length=100), nullable=False, comment='包名'),
    sa.Column('appActivity', sa.String(length=100), nullable=False, comment='启动页'),
    sa.Column('automationName', sa.String(length=100), nullable=False, comment='automationName'),
    sa.Column('noReset', sa.String(length=100), nullable=False, comment='在当前 session 下不会重置应用的状态。'),
    sa.Column('dontStopAppOnRest', sa.String(length=100), nullable=False, comment='(仅安卓) 用于设置appium重启时是否先杀掉app'),
    sa.Column('autoGrantPermissions', sa.String(length=100), nullable=False, comment='自动确定您的应用需要哪些权限'),
    sa.Column('systemPort', sa.String(length=100), nullable=False, comment='并发执行时需要用到'),
    sa.Column('remoteHost', sa.String(length=100), nullable=False, comment='远程appium服务器地址'),
    sa.Column('remotePort', sa.String(length=100), nullable=False, comment='远程appium服务器端口'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_management')
    # ### end Alembic commands ###
