"""empty message

Revision ID: 09afb073f395
Revises: f0e4ed604c6e
Create Date: 2019-12-02 15:59:30.036260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09afb073f395'
down_revision = 'f0e4ed604c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('id_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.add_column('project', sa.Column('id_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.add_column('test_case', sa.Column('id_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.add_column('test_case_suit', sa.Column('id_del', sa.Integer(), nullable=False, comment='是否已删除'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit', 'id_del')
    op.drop_column('test_case', 'id_del')
    op.drop_column('project', 'id_del')
    op.drop_column('page', 'id_del')
    # ### end Alembic commands ###
