"""empty message

Revision ID: 0a1251b251bd
Revises: 17f107ba37db
Create Date: 2019-08-30 17:58:42.517212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a1251b251bd'
down_revision = '17f107ba37db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Function_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='方法名'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='所属系统：通用，Android，IOS，PC'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='方法说明'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('function_info')
    op.drop_constraint('action_ibfk_2', 'action', type_='foreignkey')
    op.drop_constraint('action_ibfk_3', 'action', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('action_ibfk_3', 'action', 'function_info', ['fun_id'], ['id'])
    op.create_foreign_key('action_ibfk_2', 'action', 'element', ['ele_id'], ['id'])
    op.create_table('function_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False, comment='方法名'),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True, comment='所属系统：通用，Android，IOS，PC'),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True, comment='方法说明'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Function_info')
    # ### end Alembic commands ###
