"""empty message

Revision ID: 0b23f45f2040
Revises: b09c81068c8d
Create Date: 2019-09-09 14:24:43.173023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b23f45f2040'
down_revision = 'b09c81068c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_case_ibfk_1', 'test_case', type_='foreignkey')
    op.drop_column('test_case', 'suit_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('suit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用例集id'))
    op.create_foreign_key('test_case_ibfk_1', 'test_case', 'test_case_suit', ['suit_id'], ['id'])
    # ### end Alembic commands ###
