"""empty message

Revision ID: 17f107ba37db
Revises: ca9f1e2babca
Create Date: 2019-08-30 17:44:13.540245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f107ba37db'
down_revision = 'ca9f1e2babca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action', 'element', ['ele_id'], ['id'])
    op.create_foreign_key(None, 'action', 'function_info', ['fun_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_constraint(None, 'action', type_='foreignkey')
    # ### end Alembic commands ###
