"""empty message

Revision ID: 1b2c5be1e43f
Revises: 651899c09c2f
Create Date: 2019-09-25 14:15:31.645534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2c5be1e43f'
down_revision = '651899c09c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_info', sa.Column('fun_title', sa.String(length=100), nullable=False, comment='方法名'))
    op.create_unique_constraint(None, 'function_info', ['fun_title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'function_info', type_='unique')
    op.drop_column('function_info', 'fun_title')
    # ### end Alembic commands ###
