"""empty message

Revision ID: 29af66db1096
Revises: 7daa93d34714
Create Date: 2019-12-10 10:49:01.694335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29af66db1096'
down_revision = '7daa93d34714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤结束时间',
               existing_nullable=True)
    op.drop_column('test_case_suit_log', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit_log', sa.Column('uid', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试步骤结束时间',
               existing_nullable=True)
    # ### end Alembic commands ###
