"""empty message

Revision ID: 2af0fe2c10e7
Revises: b0d29211bb4e
Create Date: 2020-01-22 09:41:42.515605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2af0fe2c10e7'
down_revision = 'b0d29211bb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('element', 'loc_for_android',
               existing_type=mysql.VARCHAR(length=200),
               comment='Android信息描述',
               existing_comment='信息描述',
               existing_nullable=True)
    op.alter_column('element', 'loc_for_ios',
               existing_type=mysql.VARCHAR(length=200),
               comment='IOS信息描述',
               existing_comment='信息描述',
               existing_nullable=True)
    op.alter_column('element', 'type_for_android',
               existing_type=mysql.VARCHAR(length=30),
               comment='Android查找方式',
               existing_comment='查找方式',
               existing_nullable=True)
    op.alter_column('element', 'type_for_ios',
               existing_type=mysql.VARCHAR(length=30),
               comment='IOS查找方式',
               existing_comment='查找方式',
               existing_nullable=True)
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例结束时间',
               existing_nullable=True)
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试用例开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试用例结束时间',
               existing_nullable=True)
    op.alter_column('element', 'type_for_ios',
               existing_type=mysql.VARCHAR(length=30),
               comment='查找方式',
               existing_comment='IOS查找方式',
               existing_nullable=True)
    op.alter_column('element', 'type_for_android',
               existing_type=mysql.VARCHAR(length=30),
               comment='查找方式',
               existing_comment='Android查找方式',
               existing_nullable=True)
    op.alter_column('element', 'loc_for_ios',
               existing_type=mysql.VARCHAR(length=200),
               comment='信息描述',
               existing_comment='IOS信息描述',
               existing_nullable=True)
    op.alter_column('element', 'loc_for_android',
               existing_type=mysql.VARCHAR(length=200),
               comment='信息描述',
               existing_comment='Android信息描述',
               existing_nullable=True)
    # ### end Alembic commands ###
