"""empty message

Revision ID: 356f94ea6275
Revises: 0a1251b251bd
Create Date: 2019-09-04 17:59:31.179884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356f94ea6275'
down_revision = '0a1251b251bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('action_ibfk_2', 'action', type_='foreignkey')
    op.drop_constraint('action_ibfk_3', 'action', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('action_ibfk_3', 'action', 'function_info', ['fun_id'], ['id'])
    op.create_foreign_key('action_ibfk_2', 'action', 'element', ['ele_id'], ['id'])
    # ### end Alembic commands ###
