"""empty message

Revision ID: 49e1fc210458
Revises: 7e67fb00f90e
Create Date: 2019-12-09 15:41:10.411448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e1fc210458'
down_revision = '7e67fb00f90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case_suit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_suit_id', sa.Integer(), nullable=True, comment='测试集ID'),
    sa.Column('test_case_suit_title', sa.String(length=100), nullable=False, comment='测试集标题'),
    sa.Column('equipment_title', sa.String(length=100), nullable=False, comment='设备'),
    sa.Column('equipment_args', sa.Text(), nullable=True, comment='设备配置参数'),
    sa.Column('run_test_result', sa.Integer(), nullable=False, comment='测试执行结果:0失败,1成功'),
    sa.Column('run_test_suit_start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='测试执行开始时间'),
    sa.Column('run_test_suit_end_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='测试执行结束时间'),
    sa.ForeignKeyConstraint(['test_case_suit_id'], ['test_case_suit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True, comment='测试用例ID'),
    sa.Column('test_case_title', sa.String(length=100), nullable=False, comment='测试用例标题'),
    sa.Column('test_case_step_id', sa.Integer(), nullable=True, comment='测试用例步骤ID'),
    sa.Column('test_case_action_title', sa.String(length=100), nullable=False, comment='测试操作标题'),
    sa.Column('test_case_action_input', sa.String(length=100), nullable=False, comment='测试操作输入参数'),
    sa.Column('test_case_action_output', sa.String(length=100), nullable=False, comment='测试操作输出参数'),
    sa.Column('test_case_suit_log_id', sa.Integer(), nullable=True, comment='所属测试集日志ID'),
    sa.Column('run_test_action_result', sa.Integer(), nullable=False, comment='测试操作执行结果:0失败,1成功'),
    sa.Column('action_start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='测试步骤开始时间'),
    sa.Column('action_end_time', sa.DateTime(), nullable=False, comment='测试步骤结束时间'),
    sa.ForeignKeyConstraint(['test_case_suit_log_id'], ['test_case_suit_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case_log')
    op.drop_table('test_case_suit_log')
    # ### end Alembic commands ###
