"""empty message

Revision ID: 4f6eb5428fe8
Revises: 5793e9dbbe09
Create Date: 2019-10-12 09:53:58.081723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6eb5428fe8'
down_revision = '5793e9dbbe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_step', sa.Column('skip', sa.Integer(), nullable=False, comment='是否略过'))
    op.add_column('test_suit_step', sa.Column('skip', sa.Integer(), nullable=False, comment='是否略过'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suit_step', 'skip')
    op.drop_column('test_case_step', 'skip')
    # ### end Alembic commands ###
