"""empty message

Revision ID: 50f1f96c6e2c
Revises: ff2f77bddab6
Create Date: 2019-11-08 15:37:21.305893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f1f96c6e2c'
down_revision = 'ff2f77bddab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action', 'element', ['ele_id'], ['id'])
    op.add_column('test_case_step', sa.Column('take_screen_shot', sa.Boolean(), nullable=False, comment='是否截图'))
    op.add_column('test_case_step', sa.Column('wait_time', sa.Integer(), nullable=True, comment='用例等待时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_step', 'wait_time')
    op.drop_column('test_case_step', 'take_screen_shot')
    op.drop_constraint(None, 'action', type_='foreignkey')
    # ### end Alembic commands ###
