"""empty message

Revision ID: 5793e9dbbe09
Revises: bdbbaedb4636
Create Date: 2019-10-10 14:18:59.436910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5793e9dbbe09'
down_revision = 'bdbbaedb4636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suit_step', 'isSkip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_suit_step', sa.Column('isSkip', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否略过'))
    # ### end Alembic commands ###
