"""empty message

Revision ID: 5a838508dbd6
Revises: a86c361833ad
Create Date: 2019-11-09 17:40:34.592609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a838508dbd6'
down_revision = 'a86c361833ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_include_test_suit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False, comment='设备ID'),
    sa.Column('test_case_suit_id', sa.Integer(), nullable=True, comment='测试集ID'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_management.id'], ),
    sa.ForeignKeyConstraint(['test_case_suit_id'], ['test_case_suit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_args')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_args',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cycle_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='第几次循环'),
    sa.Column('key', mysql.VARCHAR(length=100), nullable=False, comment='参数名'),
    sa.Column('value', mysql.TEXT(), nullable=True, comment='参数值'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('equipment_include_test_suit')
    # ### end Alembic commands ###
