"""empty message

Revision ID: 5d1dfac9d830
Revises: f3e8f2bdafe6
Create Date: 2019-09-17 14:06:11.502691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d1dfac9d830'
down_revision = 'f3e8f2bdafe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_action',
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], )
    )
    op.alter_column('function_info', 'type',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属系统：0通用，1:Android，2:IOS，3:PC',
               existing_comment='所属系统：通用，1:Android，2:IOS，3:PC',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('function_info', 'type',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属系统：通用，1:Android，2:IOS，3:PC',
               existing_comment='所属系统：0通用，1:Android，2:IOS，3:PC',
               existing_nullable=True)
    op.drop_table('case_action')
    # ### end Alembic commands ###
