"""empty message

Revision ID: 651899c09c2f
Revises: 0763ac7124a4
Create Date: 2019-09-24 14:27:28.194206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651899c09c2f'
down_revision = '0763ac7124a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_management', sa.Column('title', sa.String(length=100), nullable=False, comment='配置名'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_management', 'title')
    # ### end Alembic commands ###
