"""empty message

Revision ID: 69353bd4549c
Revises: 92a54c92fcb7
Create Date: 2019-09-17 16:19:59.329994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69353bd4549c'
down_revision = '92a54c92fcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'test_case_step', 'action', ['action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case_step', type_='foreignkey')
    # ### end Alembic commands ###
