"""empty message

Revision ID: 77df1ad5e08e
Revises: ea11353d6e88
Create Date: 2019-09-17 14:47:26.113577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77df1ad5e08e'
down_revision = 'ea11353d6e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=False, comment='用例名'),
    sa.Column('test_case_id', sa.Integer(), nullable=True, comment='所属项目ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_step_action',
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('test_case_step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['test_case_step_id'], ['test_case_step.id'], )
    )
    op.drop_table('case_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_action',
    sa.Column('action_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('test_case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], name='case_action_ibfk_1'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='case_action_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('case_step_action')
    op.drop_table('test_case_step')
    # ### end Alembic commands ###
