"""empty message

Revision ID: 7daa93d34714
Revises: 93089057b652
Create Date: 2019-12-09 17:51:21.429386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7daa93d34714'
down_revision = '93089057b652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_log', sa.Column('error_msg', sa.Text(), nullable=True, comment='错误信息'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤结束时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试步骤结束时间',
               existing_nullable=True)
    op.drop_column('test_case_log', 'error_msg')
    # ### end Alembic commands ###
