"""empty message

Revision ID: 7e67fb00f90e
Revises: 09afb073f395
Create Date: 2019-12-02 16:06:52.874286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e67fb00f90e'
down_revision = '09afb073f395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('is_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.drop_column('page', 'id_del')
    op.add_column('project', sa.Column('is_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.drop_column('project', 'id_del')
    op.add_column('test_case', sa.Column('is_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.drop_column('test_case', 'id_del')
    op.add_column('test_case_suit', sa.Column('is_del', sa.Integer(), nullable=False, comment='是否已删除'))
    op.drop_column('test_case_suit', 'id_del')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit', sa.Column('id_del', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='是否已删除'))
    op.drop_column('test_case_suit', 'is_del')
    op.add_column('test_case', sa.Column('id_del', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='是否已删除'))
    op.drop_column('test_case', 'is_del')
    op.add_column('project', sa.Column('id_del', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='是否已删除'))
    op.drop_column('project', 'is_del')
    op.add_column('page', sa.Column('id_del', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='是否已删除'))
    op.drop_column('page', 'is_del')
    # ### end Alembic commands ###
