"""empty message

Revision ID: 81cdde392dd3
Revises: 6f299b218776
Create Date: 2019-12-12 10:43:31.501259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81cdde392dd3'
down_revision = '6f299b218776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_management', sa.Column('next_run_time', sa.String(length=100), nullable=True, comment='下次任务运行时间'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤结束时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试步骤结束时间',
               existing_nullable=True)
    op.drop_column('equipment_management', 'next_run_time')
    # ### end Alembic commands ###
