"""empty message

Revision ID: 8829b5c1d86c
Revises: 1d5b3b032bce
Create Date: 2019-09-26 16:35:07.202236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8829b5c1d86c'
down_revision = '1d5b3b032bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_management', sa.Column('status', sa.Integer(), nullable=False, comment='运行状态 0停止,1运行中'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_management', 'status')
    # ### end Alembic commands ###
