"""empty message

Revision ID: 9098af93affc
Revises: af799c25cab6
Create Date: 2019-10-10 14:02:14.201985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9098af93affc'
down_revision = 'af799c25cab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_args', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'))
    op.add_column('test_args', sa.Column('cycle_time', sa.Integer(), nullable=False, comment='第几次循环'))
    op.add_column('test_args', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.drop_constraint('test_args_ibfk_1', 'test_args', type_='foreignkey')
    op.drop_column('test_args', 'test_case_id')
    op.drop_column('test_args', 'test_suit_step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_args', sa.Column('test_suit_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('test_args', sa.Column('test_case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='用例ID,方便用例入参依赖,可根据用例ID查找到该用例输入或输出的参数'))
    op.create_foreign_key('test_args_ibfk_1', 'test_args', 'test_suit_step', ['test_suit_step_id'], ['id'])
    op.drop_column('test_args', 'update_datetime')
    op.drop_column('test_args', 'cycle_time')
    op.drop_column('test_args', 'create_datetime')
    # ### end Alembic commands ###
