"""empty message

Revision ID: 92a54c92fcb7
Revises: a0d7885fc09d
Create Date: 2019-09-17 16:10:56.370289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92a54c92fcb7'
down_revision = 'a0d7885fc09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_step', sa.Column('action_id', sa.Integer(), nullable=False, comment='执行动作'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_case_step', type_='foreignkey')
    op.drop_column('test_case_step', 'action_id')
    op.create_table('case_step_action',
    sa.Column('action_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('test_case_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_step_id'], ['test_case_step.id'], name='case_step_action_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
