"""empty message

Revision ID: 93089057b652
Revises: ac5fa34fe37c
Create Date: 2019-12-09 16:56:41.620068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93089057b652'
down_revision = 'ac5fa34fe37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='测试步骤结束时间')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='测试步骤结束时间')
    # ### end Alembic commands ###
