"""empty message

Revision ID: 9eee04180cfe
Revises: ea826ddfa8ee
Create Date: 2019-09-17 14:15:56.609445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eee04180cfe'
down_revision = 'ea826ddfa8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_to_suit',
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('test_case_suit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_case_suit_id'], ['test_case_suit.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_to_suit')
    # ### end Alembic commands ###
