"""empty message

Revision ID: a0d7885fc09d
Revises: 77df1ad5e08e
Create Date: 2019-09-17 15:39:58.848767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0d7885fc09d'
down_revision = '77df1ad5e08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_step', 'rank',
               existing_type=mysql.VARCHAR(length=100),
               comment='步骤',
               existing_comment='用例名',
               existing_nullable=False)
    op.alter_column('test_case_step', 'test_case_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='所属用例ID',
               existing_comment='所属项目ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_step', 'test_case_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='所属项目ID',
               existing_comment='所属用例ID',
               existing_nullable=True)
    op.alter_column('test_case_step', 'rank',
               existing_type=mysql.VARCHAR(length=100),
               comment='用例名',
               existing_comment='步骤',
               existing_nullable=False)
    # ### end Alembic commands ###
