"""empty message

Revision ID: a86c361833ad
Revises: 50f1f96c6e2c
Create Date: 2019-11-08 15:38:02.981367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a86c361833ad'
down_revision = '50f1f96c6e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_step', 'wait_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='用例等待时间')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_step', 'wait_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='用例等待时间')
    # ### end Alembic commands ###
