"""empty message

Revision ID: ac5fa34fe37c
Revises: dcea50cf2201
Create Date: 2019-12-09 16:45:05.124755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac5fa34fe37c'
down_revision = 'dcea50cf2201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_log', sa.Column('test_case_step_rank', sa.Integer(), nullable=True, comment='测试用例步骤'))
    op.alter_column('test_case_log', 'run_test_action_result',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='测试操作执行结果:0失败,1成功')
    op.alter_column('test_case_log', 'test_case_action_input',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True,
               existing_comment='测试操作输入参数')
    op.alter_column('test_case_log', 'test_case_action_output',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True,
               existing_comment='测试操作输出参数')
    op.drop_column('test_case_log', 'test_case_step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_log', sa.Column('test_case_step_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='测试用例步骤ID'))
    op.alter_column('test_case_log', 'test_case_action_output',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False,
               existing_comment='测试操作输出参数')
    op.alter_column('test_case_log', 'test_case_action_input',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False,
               existing_comment='测试操作输入参数')
    op.alter_column('test_case_log', 'run_test_action_result',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='测试操作执行结果:0失败,1成功')
    op.drop_column('test_case_log', 'test_case_step_rank')
    # ### end Alembic commands ###
