"""empty message

Revision ID: ad6734b2358e
Revises: e3909e784a1f
Create Date: 2019-12-13 17:56:37.357050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad6734b2358e'
down_revision = 'e3909e784a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False, comment='设备ID'),
    sa.Column('equipment_title', sa.String(length=100), nullable=False, comment='设备'),
    sa.Column('equipment_args', sa.Text(), nullable=True, comment='设备配置参数'),
    sa.Column('run_test_result', sa.Integer(), nullable=False, comment='测试执行结果:0失败,1成功'),
    sa.Column('run_test_start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='测试执行开始时间'),
    sa.Column('run_test_end_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='测试执行结束时间'),
    sa.Column('run_test_times', sa.String(length=100), nullable=True, comment='测试执行用时时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_case_log', sa.Column('run_test_case_times', sa.String(length=100), nullable=True, comment='测试用例执行用时'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤结束时间',
               existing_nullable=True)
    op.add_column('test_case_suit_log', sa.Column('run_test_suit_times', sa.String(length=100), nullable=True, comment='测试集执行用时'))
    op.add_column('test_case_suit_log', sa.Column('test_log_id', sa.Integer(), nullable=True, comment='所属测试日志ID'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行结束时间',
               existing_comment='测试执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行开始时间',
               existing_comment='测试执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'test_case_suit_log', 'test_log', ['test_log_id'], ['id'])
    op.drop_column('test_case_suit_log', 'equipment_id')
    op.drop_column('test_case_suit_log', 'equipment_args')
    op.drop_column('test_case_suit_log', 'equipment_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit_log', sa.Column('equipment_title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False, comment='设备'))
    op.add_column('test_case_suit_log', sa.Column('equipment_args', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='设备配置参数'))
    op.add_column('test_case_suit_log', sa.Column('equipment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='设备ID'))
    op.drop_constraint(None, 'test_case_suit_log', type_='foreignkey')
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试执行开始时间',
               existing_comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试执行结束时间',
               existing_comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_column('test_case_suit_log', 'test_log_id')
    op.drop_column('test_case_suit_log', 'run_test_suit_times')
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试步骤结束时间',
               existing_nullable=True)
    op.drop_column('test_case_log', 'run_test_case_times')
    op.drop_table('test_log')
    # ### end Alembic commands ###
