"""empty message

Revision ID: af799c25cab6
Revises: 6282a570de50
Create Date: 2019-10-10 11:57:12.303539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af799c25cab6'
down_revision = '6282a570de50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_args', sa.Column('test_suit_step_id', sa.Integer(), nullable=False))
    op.alter_column('test_args', 'test_case_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用例ID,方便用例入参依赖,可根据用例ID查找到该用例输入或输出的参数',
               existing_nullable=False)
    op.drop_constraint('test_args_ibfk_1', 'test_args', type_='foreignkey')
    op.create_foreign_key(None, 'test_args', 'test_suit_step', ['test_suit_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_args', type_='foreignkey')
    op.create_foreign_key('test_args_ibfk_1', 'test_args', 'test_case', ['test_case_id'], ['id'])
    op.alter_column('test_args', 'test_case_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用例ID,方便用例入参依赖,可根据用例ID查找到该用例输入或输出的参数',
               existing_nullable=False)
    op.drop_column('test_args', 'test_suit_step_id')
    # ### end Alembic commands ###
