"""empty message

Revision ID: b09c81068c8d
Revises: 356f94ea6275
Create Date: 2019-09-06 11:44:40.973119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b09c81068c8d'
down_revision = '356f94ea6275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('function_info', 'type',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属系统：通用，1:Android，2:IOS，3:PC',
               existing_comment='所属系统：通用，Android，IOS，PC',
               existing_nullable=True)
    op.create_unique_constraint(None, 'function_info', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'function_info', type_='unique')
    op.alter_column('function_info', 'type',
               existing_type=mysql.VARCHAR(length=100),
               comment='所属系统：通用，Android，IOS，PC',
               existing_comment='所属系统：通用，1:Android，2:IOS，3:PC',
               existing_nullable=True)
    # ### end Alembic commands ###
