"""empty message

Revision ID: b0d29211bb4e
Revises: ebc1fea11731
Create Date: 2020-01-22 09:37:07.382000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0d29211bb4e'
down_revision = 'ebc1fea11731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('loc_for_android', sa.String(length=200), nullable=True, comment='信息描述'))
    op.add_column('element', sa.Column('loc_for_ios', sa.String(length=200), nullable=True, comment='信息描述'))
    op.add_column('element', sa.Column('type_for_android', sa.String(length=30), nullable=True, comment='查找方式'))
    op.add_column('element', sa.Column('type_for_ios', sa.String(length=30), nullable=True, comment='查找方式'))
    op.drop_column('element', 'type')
    op.drop_column('element', 'loc')
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例结束时间',
               existing_nullable=True)
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试用例开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_suit_log', 'run_test_suit_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_suit_log', 'run_test_suit_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试集执行结束时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'action_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试用例开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试用例结束时间',
               existing_nullable=True)
    op.add_column('element', sa.Column('loc', mysql.VARCHAR(length=200), nullable=True, comment='信息描述'))
    op.add_column('element', sa.Column('type', mysql.VARCHAR(length=30), nullable=True, comment='查找方式'))
    op.drop_column('element', 'type_for_ios')
    op.drop_column('element', 'type_for_android')
    op.drop_column('element', 'loc_for_ios')
    op.drop_column('element', 'loc_for_android')
    # ### end Alembic commands ###
