"""empty message

Revision ID: b2e8f0c71863
Revises: 4f6eb5428fe8
Create Date: 2019-10-26 15:05:59.396219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e8f0c71863'
down_revision = '4f6eb5428fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_management', sa.Column('session_id', sa.Integer(), nullable=True, comment='session_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_management', 'session_id')
    # ### end Alembic commands ###
