"""empty message

Revision ID: b678076811fa
Revises: 8829b5c1d86c
Create Date: 2019-09-29 10:27:49.990956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b678076811fa'
down_revision = '8829b5c1d86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_step', sa.Column('input_key', sa.String(length=100), nullable=True, comment='输入参数名称'))
    op.add_column('test_case_step', sa.Column('output_key', sa.String(length=100), nullable=True, comment='输出参数名称'))
    op.add_column('test_suit_step', sa.Column('isSkip', sa.Boolean(), nullable=False, comment='是否略过'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suit_step', 'isSkip')
    op.drop_column('test_case_step', 'output_key')
    op.drop_column('test_case_step', 'input_key')
    # ### end Alembic commands ###
