"""empty message

Revision ID: bdbbaedb4636
Revises: f42021f4fcde
Create Date: 2019-10-10 14:13:05.325910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbbaedb4636'
down_revision = 'f42021f4fcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_args',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_time', sa.Integer(), nullable=False, comment='第几次循环'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='参数名'),
    sa.Column('value', sa.Text(), nullable=True, comment='参数值'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_suit_step', sa.Column('input_args', sa.Text(), nullable=True, comment='输入参数对象'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suit_step', 'input_args')
    op.drop_table('test_args')
    # ### end Alembic commands ###
