"""empty message

Revision ID: c0f28f52e96a
Revises: 396762ccb7e5
Create Date: 2019-12-02 10:29:36.987492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f28f52e96a'
down_revision = '396762ccb7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('parent_directory', sa.Integer(), nullable=False, comment='父级目录ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'parent_directory')
    # ### end Alembic commands ###
