"""empty message

Revision ID: d5f3c81a4ec5
Revises: 69353bd4549c
Create Date: 2019-09-20 17:48:15.873425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f3c81a4ec5'
down_revision = '69353bd4549c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suit_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='用例'),
    sa.Column('test_case_suit_id', sa.Integer(), nullable=True, comment='所属用例集ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['test_case_suit_id'], ['test_case_suit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_to_suit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_to_suit',
    sa.Column('test_case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('test_case_suit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], name='case_to_suit_ibfk_1'),
    sa.ForeignKeyConstraint(['test_case_suit_id'], ['test_case_suit.id'], name='case_to_suit_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('test_suit_step')
    # ### end Alembic commands ###
