"""empty message

Revision ID: dcea50cf2201
Revises: 49e1fc210458
Create Date: 2019-12-09 16:06:21.401338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcea50cf2201'
down_revision = '49e1fc210458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit_log', sa.Column('uid', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit_log', 'uid')
    # ### end Alembic commands ###
