"""empty message

Revision ID: e3909e784a1f
Revises: 81cdde392dd3
Create Date: 2019-12-12 18:59:25.362633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3909e784a1f'
down_revision = '81cdde392dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment='测试步骤结束时间',
               existing_nullable=True)
    op.add_column('test_case_suit_log', sa.Column('equipment_id', sa.Integer(), nullable=False, comment='设备ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit_log', 'equipment_id')
    op.alter_column('test_case_log', 'action_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='测试步骤结束时间',
               existing_nullable=True)
    # ### end Alembic commands ###
