"""empty message

Revision ID: ea11353d6e88
Revises: 9eee04180cfe
Create Date: 2019-09-17 14:16:58.628552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea11353d6e88'
down_revision = '9eee04180cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit', 'test_case_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit', sa.Column('test_case_ids', mysql.VARCHAR(length=100), nullable=False, comment='包含的用例ID'))
    # ### end Alembic commands ###
