"""empty message

Revision ID: ea826ddfa8ee
Revises: 5d1dfac9d830
Create Date: 2019-09-17 14:07:58.025358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea826ddfa8ee'
down_revision = '5d1dfac9d830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'action_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('action_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用例步骤id，关联action表'))
    # ### end Alembic commands ###
