"""empty message

Revision ID: f0e4ed604c6e
Revises: c0f28f52e96a
Create Date: 2019-12-02 13:59:59.556637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e4ed604c6e'
down_revision = 'c0f28f52e96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit', sa.Column('parent_directory', sa.Integer(), nullable=False, comment='父级目录ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit', 'parent_directory')
    # ### end Alembic commands ###
