"""empty message

Revision ID: f3e8f2bdafe6
Revises: 0b23f45f2040
Create Date: 2019-09-10 09:07:28.930398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e8f2bdafe6'
down_revision = '0b23f45f2040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('project_id', sa.Integer(), nullable=True, comment='所属项目ID'))
    op.create_foreign_key(None, 'test_case', 'project', ['project_id'], ['id'])
    op.add_column('test_case_suit', sa.Column('test_case_ids', sa.String(length=100), nullable=False, comment='包含的用例ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit', 'test_case_ids')
    op.drop_constraint(None, 'test_case', type_='foreignkey')
    op.drop_column('test_case', 'project_id')
    # ### end Alembic commands ###
