"""empty message

Revision ID: fc67d66a621d
Revises: d5f3c81a4ec5
Create Date: 2019-09-20 20:16:44.066744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc67d66a621d'
down_revision = 'd5f3c81a4ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case_suit', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case_suit', sa.Column('description', mysql.VARCHAR(length=100), nullable=True, comment='说明'))
    # ### end Alembic commands ###
