"""empty message

Revision ID: ff2f77bddab6
Revises: b2e8f0c71863
Create Date: 2019-11-07 11:33:18.744948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2f77bddab6'
down_revision = 'b2e8f0c71863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'action', 'function_info', ['fun_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'action', type_='foreignkey')
    # ### end Alembic commands ###
